/****************************************************************************
 **
 ** ��Ȩ���� (C) 2006-2007 ���Ĺ�˾.
 **
 ****************************************************************************/
#ifndef BEAMERKEYWORD_H
#define BEAMERKEYWORD_H

#define BEAMER_MIN_KEYWORD 100000

enum BeamerKeyWord
{
	BMmode  = BEAMER_MIN_KEYWORD,

	BMusetheme,
	BMuseinnertheme,
	BMuseoutertheme,
	BMusecolortheme,
	BMusefonttheme,

	BMusebeamertemplate,
	BMifbeamertemplateempty,
	BMexpandbeamertemplate,

	BMsetbeamertemplate,
	BMaddtobeamertemplate,
	BMdefbeamertemplate,
	BMdefbeamertemplatealias,
	BMdefbeamertemplateparent,

	BMusebeamercolor,
	BMifbeamercolorempty,

	BMsetbeamercolor,
	BMsetbeamercovered,
	BMopaqueness,

	BMusebeamerfont,

	BMsetbeamerfont,

	BMsetbeameroption,

	BMsetbeamersize,

	BMsetjobnamebeamerversion,

	BMnewcommand,
	BMrenewcommand,
	BMnewenvironment,
	BMrenewenvironment,

	BMAtBeginLecture,
	BMAtBeginPart,
	BMAtBeginSection,
	BMAtBeginSubsection,
	BMAtBeginSubsubsection,
	BMAtBeginNote,
	BMAtEndNote,

	BMtitle,
	BMsubtitle,
	BMauthor,
	BMinstitute,
	BMdate,
	BMtitlegraphic,
	BMsubject,
	BMkeywords,

	BMincludeonlylecture,

	BMmaketitle,

	BMlecture,
	BMpart,
	BMsection,
	BMsubsection,
	BMsubsubsection,

	BMappendix,

	BMframe,

	BMlogo,
	BMframetitle,
	BMframesubtitle,
	BMtableofcontents,

	BMhypertarget,
	BMbeamerbutton,
	BMbeamergotobutton,
	BMbeamerskipbutton,
	BMbeamerreturnbutton,
	BMhyperlink,
	BMhyperlinkslideprev,
	BMhyperlinkslidenext,
	BMhyperlinkframestart,
	BMhyperlinkframeend,
	BMhyperlinkframestartnext,
	BMhyperlinkframeendprev,
	BMhyperlinkpresentationstart,
	BMhyperlinkpresentationend,
	BMhyperlinkappendixstart,
	BMhyperlinkappendixend,
	BMhyperlinkdocumentstart,
	BMhyperlinkdocumentend,
	BMagainframe,
	BMframezoom,

	BMaddheadbox,
	BMaddfootbox,

	BMmovie,
	BMhyperlinkmovie,
	BManimate,
	BManimatevalue,
	BMmultiinclude,
	BMsound,
	BMhyperlinksound,
	BMhyperlinkmute,

	BMtransblindshorizontal,
	BMtransblindsvertical,
	BMtransboxin,
	BMtransboxout,
	BMtransdissolve,
	BMtransglitter,
	BMtransreplace,
	BMtranssplitverticalin,
	BMtranssplitverticalout,
	BMtranssplithorizontalin,
	BMtranssplithorizontalout,
	BMtranswipe,
	BMtransduration,

	BMitem,
	BMlabel,
	BMbibitem,
	BMcolumn,

	BMnote,

	BMpause,
	BMonslide,
	BMonly,
	BMuncover,
	BMvisible,
	BMinvisible,
	BMalt,
	BMtemporal,
	BMresetcounteronoverlays,
	BMresetcountonoverlays,
	BMaction,
	BMbeamerdefaultoverlayspecification,
	BMstructure,
	BMalert,
	BMincludeslide,

	BMbegin,
	BMend,

	//inserts
	BMtitlepage,
	BMpartpage,

	BMinsertauthor,
	BMinsertdate,
	BMinsertinstitute,
	BMinserttitle,
	BMinsertsubtitle,
	BMinserttitlegraphic,

	BMinsertpart,
	BMinsertpartnumber,
	BMinsertpartromannumber,

	BMinserttocsection,
	BMinserttocsectionnumber,
	BMinserttocsubsection,
	BMinserttocsubsectionnumber,
	BMinserttocsubsubsection,
	BMinserttocsubsubsectionnumber,

	BMinsertcontinuationcount,
	BMinsertcontinuationcountroman,
	BMinsertcontinuationtext,

	BMinsertnavigation,
	BMinsertpagenumber,
	BMinsertsection,
	BMinsertsectionnavigation,
	BMinsertsectionnavigationhorizontal,
	BMinsertshortauthor,
	BMinsertshortdate,
	BMinsertshortinstitute,
	BMinsertshortpart,
	BMinsertshorttitle,
	BMinsertshortsubtitle,
	BMinsertsubsection,
	BMinsertsubsubsection,
	BMinsertsubsectionnavigation,
	BMinsertsubsectionnavigationhorizontal,
	BMinsertverticalnavigation,
	BMinsertframenumber,
	BMinserttotalframenumber,
	BMinsertframestartpage,
	BMinsertframeendpage,
	BMinsertsubsectionstartpage,
	BMinsertsubsectionendpage,
	BMinsertsectionstartpage,
	BMinsertsectionendpage,
	BMinsertpartstartpage,
	BMinsertpartendpage,
	BMinsertpresentationstartpage,
	BMinsertpresentationendpage,
	BMinsertappendixstartpage,
	BMinsertappendixendpage,
	BMinsertdocumentstartpage,
	BMinsertdocumentendpage,

	BMinsertsectionhead,
	BMinsertsectionheadnumber,
	BMinsertpartheadnumber,

	BMinsertsubsectionhead,
	BMinsertsubsectionheadnumber,

	BMinsertsubsubsectionhead,
	BMinsertsubsubsectionheadnumber,

	BMinsertslidenavigationsymbol,
	BMinsertframenavigationsymbol,
	BMinsertsubsectionnavigationsymbol,
	BMinsertsectionnavigationsymbol,
	BMinsertdocnavigationsymbol,
	BMinsertbackfindforwardnavigationsymbol,

	BMinsertlogo,

	BMinsertframetitle,
	BMinsertframesubtitle,

	BMinsertbiblabel,

	BMinsertbuttontext,
	BMinsertgotosymbol,
	BMinsertskipsymbol,
	BMinsertreturnsymbol,

	BMinsertenumlabel,
	BMinsertsubenumlabel,
	BMinsertsubsubenumlabel,

	BMinsertdescriptionitem,

	BMinsertblocktitle,

	BMinserttheoremblockenv,
	BMinserttheoremheadfont,
	BMinserttheoremname,
	BMinserttheoremnumber,
	BMinserttheoremaddition,
	BMinserttheorempunctuation,

	BMinsertcaption,
	BMinsertcaptionname,
	BMinsertcaptionnumber,

	//class option
	BMhandout,
	BMtrans,
	BMaspectratio,
	BM8pt,
	BM9pt,
	BM10pt,
	BMsmaller,
	BM11pt,
	BM12pt,
	BMbigger,
	BM14pt,
	BM17pt,
	BM20pt,
	BMdraft,
	BMcompress,
	BMb,
	BMc,
	BMt,
	BMcolor,
	BMxcolor,
	BMucs,
	BMutf8x,
	BMutf8,
	BMprosper,
	BMseminar,
	BMfoils,
	BMhyperref,
	BMusepdftitle,
	BMenvcountsect,
	BMnotheorems,
	BMnoamsthm,

	//mode
	BMbeamer,
	BMsecond,
	BMarticle,
	BMall,
	BMpresentation,

	//Presentation Themes
	BMdefault,
	BMboxes,
	BMBergen,
	BMBoadilla,
	BMMadrid,
	BMAnnArbor,
	BMCambridgeUS,
	BMPittsburgh,
	BMRochester,
	BMAntibes,
	BMJuanLesPins,
	BMMontpellier,
	BMBerkeley,
	BMPaloAlto,
	BMGoettingen,
	BMMarburg,
	BMHannover,
	BMBerlin,
	BMIlmenau,
	BMDresden,
	BMDarmstadt,
	BMFrankfurt,
	BMSingapore,
	BMSzeged,
	BMCopenhagen,
	BMLuebeck,
	BMMalmoe,
	BMWarsaw,

	//Inner Themes
	BMcircles,
	BMrectangles,
	BMrounded,
	BMinmargin,

	//Outer Themes
	BMinfolines,
	BMminiframes,
	BMsmoothbars,
	BMsidebar,
	BMsplit,
	BMshadow,
	BMtree,
	BMsmoothtree,

	//Color Themes
	BMsidebartab,
	BMalbatross,
	BMbeetle,
	BMcrane,
	BMdove,
	BMfly,
	BMseagull,
	BMwolverine,
	BMbeaver,
	BMlily,
	BMorchid,
	BMrose,
	BMwhale,
	BMseahorse,
	BMdolphin,

	//Font Themes
	BMprofessionalfonts,
	BMserif,
	BMstructurebold,
	BMstructureitalicserif,
	BMstructuresmallcapsserif,

	//Presentation Themes Options
	//boxes
	BMheadheight,
	BMfootheight,
	//Boadilla, Madrid
	BMsecheader,
	//Rochester
	BMheight,
	//Berkeley, PaloAlto, Goettingen, Marburg, Hannover
	BMhideallsubsections,
	BMhideothersubsections,
	BMleft,
	BMright,
	BMwidth,

	//Inner Themes Options

	//Outer Themes Options
	BMfootline,
	BMhooks,

	//Color Themes Options
	BMrgb,
	BMcmyk,
	BMcmy,
	BMhsb,
	BMnamed,
	BMoverlystylish,

	//Font Themes Options
	BMstillsansserifmath,
	BMstillsansserifsmall,
	BMstillsansseriflarge,
	BMstillsansseriftext,
	BMonlymath,
	BMonlysmall,
	BMonlylarge,

	//

	//template/color/font
	BMFrameTitleContinuation,
	BMheadline,
	//BMfootline
	BMSidebarLeft,
	BMSidebarRight,
	BMMiniFrame,
	BMSectionInHFoot,
	BMSectionInSidebar,
	BMSubsectionInHFoot,
	BMSubsectionInSidebar,
	BMSubsubsectionInHFoot,
	BMSubsubsectionInSidebar,
	BMNavigationSymbols,
	//BMlogo
	//BMframetitle
	//BMframesubtitle
	BMBackgroundCanvas,
	BMbackground,
	BMTitlePage,
	BMSectionInToc,
	BMSectionInTocShaded,
	BMSubsectionInToc,
	BMSubsectionInTocShaded,
	BMSubsubsectionInToc,
	BMSubsubsectionInTocShaded,
	BMPartPage,
	BMBibEntryAuthor,
	BMBibEntryTitle,
	BMBibEntryJournal,
	BMBibEntryNote,
	BMBibItem,
	BMbutton,
	BMItemizeItem,
	BMItemizeSubitem,
	BMItemizeSubsubitem,
	BMEnumerateItem,
	BMEnumerateSubitem,
	BMEnumerateSubsubitem,
	BMEnumerateMiniTemplate,
	BMDescriptionItem,
	BMQedSymbol,
	BMcaption,
	BMAbstractTitle,
	//BMfootnote,
	BMNotePage,

	//template
	BMFrameBegin,
	BMFrameEnd,
	BMSidebarCanvasLeft,
	BMSidebarCanvasRight,
	BMMiniFrames,
	BMMiniFrameInCurSubsection,
	BMMiniFrameInOtherSubsection,
	BMSectionInHFootShaded,
	BMSectionInSidebarShaded,
	BMSubsectionInHFootShaded,
	BMSubsectionInSidebarShaded,
	BMSubsubsectionInHFootShaded,
	BMSubsubsectionInSidebarShaded,
	BMSectionsSubsectionsInToc,
	BMSectionsSubsectionsInTocShaded,
	BMItemizeItems,
	BMEnumerateItems,
	BMItemEnumBodyBegin,
	BMItemEnumBodyEnd,
	BMitems,
	BMStructureBegin,
	BMStructureEnd,
	BMAlertedTextBegin,
	BMAlertedTextEnd,
	BMblocks,
	BMBlockBegin,
	BMBlockEnd,
	BMBlockAlertedBegin,
	BMBlockAlertedEnd,
	BMBlockExampleBegin,
	BMBlockExampleEnd,
	BMtheorems,
	BMTheoremBegin,
	BMTheoremEnd,
	BMAbstractBegin,
	BMAbstractEnd,
	BMVerseBegin,
	BMVerseEnd,
	BMQuotationBegin,
	BMQuotationEnd,
	BMQuoteBegin,
	BMQuoteEnd,

	//color/font
	BMPageNumberInHF,
	//BMitem
	BMItemProjected,
	BMsubitem,
	BMSubitemProjected,
	BMsubsubitem,
	BMSubsubitemProjected,
	//BMstructure
	BMAlertedText,
	BMBlockTitle,
	BMBlockBody,
	BMBlockTitleAlerted,
	BMBlockBodyAlerted,
	BMBlockTitleExample,
	BMBlockBodyExample,
	BMCaptionName,
	//BMabstract,
	//BMverse,
	//BMquotation,
	//BMquote,
	BMFootnoteMark,
	BMNormalText,
	BMExampleText,
	BMtitlelike,

	//color
	BMButtonBorder,
	BMLocalStructure,
	BMMathText,
	BMMathTextInlined,
	BMMathTextDisplayed,
	BMNormalTextInMathText,
	BMPalettePrimary,
	BMPaletteSecondary,
	BMPaletteTertiary,
	BMPaletteQuaternary,
	BMPaletteSidebarPrimary,
	BMPaletteSidebarSecondary,
	BMPaletteSidebarTertiary,
	BMPaletteSidebarQuaternary,
	BMSeparationLine,
	BMUpperSeparationLineHead,
	BMMiddleSeparationLineHead,
	BMLowerSeparationLineHead,
	BMUpperSeparationLineFoot,
	BMMiddleSeparationLineFoot,
	BMLowerSeparationLineFoot,

	//font
	BMTinyStructure,

	//template options
	BMroman,
	BMFromSecond,

	BMInfoLinesTheme,
	BMMiniFramesTheme,
	BMSidebarTheme,
	BMSmoothTreeTheme,
	BMSmoothBarsTheme,
	BMSplitTheme,
	BMTextLine,

	BMPageNumber,
	BMFrameNumber,

	BMVerticalShading,
	BMHorizontalShading,
	//
	BMtop,
	BMbottom,
	BMmiddle,
	BMmidpoint,

	BMbox,
	BMtick,

	BMhorizontal,
	BMvertical,
	BMOnlyFrameSymbol,

	BMShadowTheme,

	BMgrid,
	BMstep,

	BMSectionsNumbered,
	BMSubsectionsNumbered,
	BMcircle,
	BMsquare,
	BMball,
	BMBallUnnumbered,

	BMbook,
	BMtriangle,
	BMtext,

	BMNormalFont,
	BMnumbered,
	BMAmsStyle,

	BMCapNameOwnLine,

	BMplain,

	BMfg,
	BMbg,
	BMparent,
	BMuse,

	BMtransparent,
	BMdynamic,
	BMHighlyDynamic,
	BMStillCovered,
	BMAgainCovered,

	BMsize,
	BMSizeStar,
	BMshape,
	BMShapeStar,
	BMseries,
	BMseriesStar,
	BMfamily,
	BMFamilyStar,

	BMHideNotes,
	BMShowNotes,
	BMShowNotesOnSecond,
	BMShowOnlyNotes,
	BMSecondModeTextOnSecond,
	BMAlwaysTypesetSecondMode,
	BMPrevSlideOnSecond,

	BMTextMarginLeft,
	BMTextMarginRight,
	BMSidebarWidthLeft,
	BMSidebarWidthRight,
	BMDescriptionWidth,
	BMDescriptionWidthOf,
	BMMiniFrameSize,
	BMMiniFrameOffset,

	//frame opt
	BMallowdisplaybreaks,
	BMallowframebreaks,
	BMfragile,
	BMenvironment,
	BMshrink,
	BMsqueeze,

	//TOC Opt
	BMcurrentsection,
	BMcurrentsubsection,
	BMfirstsection,
	BMpausesections,
	BMpausesubsections,
	BMsections,
	BMsectionstyle,
	BMsubsectionstyle,

	BMborder,

	BMautostart,
	BMborderwidth,
	BMdepth,
	BMduration,
	BMexternalviewer,
	BMloop,
	BMonce,
	BMopen,
	BMpalindrome,
	BMposter,
	BMrepeat,
	BMshowcontrols,
	BMstart,

	BMplay,
	BMresume,
	BMstop,

	BMgraphics,
	BMformat,

	BMautomute,
	BMbitspersample,
	BMchannels,
	BMencoding,
	BMinlinesound,
	BMmixsound,
	BMsamplingrate,

	BMdirection,

	//env
	BMonlyenv,
	BMaltenv,
	BMoverlayarea,
	BMoverprint,

	BMactionenv,

	BMthebibliography,

	BMitemize,
	BMenumerate,
	BMdescription,

	BMstructureenv,
	BMalertenv,
	BMblock,
	BMalertblock,
	BMexampleblock,

	BMtheorem,
	BMcorollary,
	BMfact,
	BMlemma,
	BMdefinition,
	BMdefinitions,
	BMexample,
	BMexamples,

	BMproof,
	BMProblem,
	BMLoesung,
	BMDefinition,
	BMSatz,
	BMBeweis,
	BMFolgerung,
	BMLemma,
	BMFakt,
	BMBeispiel,
	BMBeispiele,

	BMbeamercolorbox,
	BMbeamerboxesrounded,

	BMcolumns,

	BMsemiverbatim,

	BMabstract,
	BMverse,
	BMquotation,
	BMquote,

	BMwd,
	BMdp,
	BMht,
	BMcenter,
	BMleftskip,
	BMrightskip,
	BMsep,
	BMcolsep,
	BMColSepStar,
	BMignorebg,
	BMvmode,

	BMlower,
	BMupper,

	BMonlytextwidth,
	BMT,
	BMtotalwidth,

	//no keyword
	BMrealparagraph,
	BMoverlayspecification,
	BMdefaultoverlayspecification,
	BMmodifier,
	BMthemeopt,
	BMthemenames,
	BMinnerthemeopt,
	BMouterthemeopt,
	BMcolorthemeopt,
	BMcolorthemenames,
	BMfontthemeopt,
	BMpredefinedopt,
	BMfontopt,
	BMframeopt,
	BMframezoomopt,
	BMmovieopt,
	BMlinkmovieopt,
	BMmultiincludeopt,
	BMsoundopt,
	BMlinksoundopt,
	BMtransopt,
	BMnoteopt,
	BMcolorboxopt,
	BMboxesroundedopt,
	BMcolumnsopt
};

#endif //BEAMERKEYWORD_H
