/****************************************************************************
 **
 ** 版权所有 (C) 2006-2007 秀文公司.
 **
 ****************************************************************************/
#include <QApplication>
#include "BeamerKeyWord.h"
#include "XWBeamerPool.h"


static const char * beamer_strings[] = {
	QT_TRANSLATE_NOOP("Beamer", "mode"),
  QT_TRANSLATE_NOOP("Beamer", "usetheme"),
  QT_TRANSLATE_NOOP("Beamer", "useinnertheme"),
  QT_TRANSLATE_NOOP("Beamer", "useoutertheme"),
  QT_TRANSLATE_NOOP("Beamer", "usecolortheme"),
  QT_TRANSLATE_NOOP("Beamer", "usefonttheme"),
  QT_TRANSLATE_NOOP("Beamer", "usebeamertemplate"),
  QT_TRANSLATE_NOOP("Beamer", "ifbeamertemplateempty"),
  QT_TRANSLATE_NOOP("Beamer", "expandbeamertemplate"),
  QT_TRANSLATE_NOOP("Beamer", "setbeamertemplate"),
  QT_TRANSLATE_NOOP("Beamer", "addtobeamertemplate"),
  QT_TRANSLATE_NOOP("Beamer", "defbeamertemplate"),
  QT_TRANSLATE_NOOP("Beamer", "defbeamertemplatealias"),
  QT_TRANSLATE_NOOP("Beamer", "defbeamertemplateparent"),
  QT_TRANSLATE_NOOP("Beamer", "usebeamercolor"),
  QT_TRANSLATE_NOOP("Beamer", "ifbeamercolorempty"),
  QT_TRANSLATE_NOOP("Beamer", "setbeamercolor"),
  QT_TRANSLATE_NOOP("Beamer", "setbeamercovered"),
  QT_TRANSLATE_NOOP("Beamer", "opaqueness"),
  QT_TRANSLATE_NOOP("Beamer", "usebeamerfont"),
  QT_TRANSLATE_NOOP("Beamer", "setbeamerfont"),
  QT_TRANSLATE_NOOP("Beamer", "setbeameroption"),
  QT_TRANSLATE_NOOP("Beamer", "setbeamersize"),
  QT_TRANSLATE_NOOP("Beamer", "newcommand"),
  QT_TRANSLATE_NOOP("Beamer", "renewcommand"),
  QT_TRANSLATE_NOOP("Beamer", "newenvironment"),
  QT_TRANSLATE_NOOP("Beamer", "renewenvironment"),
  QT_TRANSLATE_NOOP("Beamer", "AtBeginLecture"),
  QT_TRANSLATE_NOOP("Beamer", "AtBeginPart"),
  QT_TRANSLATE_NOOP("Beamer", "AtBeginSection"),
  QT_TRANSLATE_NOOP("Beamer", "AtBeginSubsection"),
  QT_TRANSLATE_NOOP("Beamer", "AtBeginSubsubsection"),
  QT_TRANSLATE_NOOP("Beamer", "AtBeginNote"),
  QT_TRANSLATE_NOOP("Beamer", "AtEndNote"),
  QT_TRANSLATE_NOOP("Beamer", "title"),
  QT_TRANSLATE_NOOP("Beamer", "subtitle"),
  QT_TRANSLATE_NOOP("Beamer", "author"),
  QT_TRANSLATE_NOOP("Beamer", "institute"),
  QT_TRANSLATE_NOOP("Beamer", "date"),
  QT_TRANSLATE_NOOP("Beamer", "titlegraphic"),
  QT_TRANSLATE_NOOP("Beamer", "subject"),
  QT_TRANSLATE_NOOP("Beamer", "keywords"),
  QT_TRANSLATE_NOOP("Beamer", "includeonlylecture"),
  QT_TRANSLATE_NOOP("Beamer", "maketitle"),
  QT_TRANSLATE_NOOP("Beamer", "lecture"),
  QT_TRANSLATE_NOOP("Beamer", "part"),
  QT_TRANSLATE_NOOP("Beamer", "section"),
  QT_TRANSLATE_NOOP("Beamer", "subsection"),
  QT_TRANSLATE_NOOP("Beamer", "subsubsection"),
  QT_TRANSLATE_NOOP("Beamer", "appendix"),
  QT_TRANSLATE_NOOP("Beamer", "frame"),
  QT_TRANSLATE_NOOP("Beamer", "logo"),
  QT_TRANSLATE_NOOP("Beamer", "frametitle"),
  QT_TRANSLATE_NOOP("Beamer", "framesubtitle"),
  QT_TRANSLATE_NOOP("Beamer", "tableofcontents"),
  QT_TRANSLATE_NOOP("Beamer", "hypertarget"),
  QT_TRANSLATE_NOOP("Beamer", "beamerbutton"),
  QT_TRANSLATE_NOOP("Beamer", "beamergotobutton"),
  QT_TRANSLATE_NOOP("Beamer", "beamerskipbutton"),
  QT_TRANSLATE_NOOP("Beamer", "beamerreturnbutton"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlink"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkslideprev"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkslidenext"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkframestart"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkframeend"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkframestartnext"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkframeendprev"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkpresentationstart"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkpresentationend"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkappendixstart"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkappendixend"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkdocumentstart"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkdocumentend"),
  QT_TRANSLATE_NOOP("Beamer", "againframe"),
  QT_TRANSLATE_NOOP("Beamer", "framezoom"),
  QT_TRANSLATE_NOOP("Beamer", "addheadbox"),
  QT_TRANSLATE_NOOP("Beamer", "addfootbox"),
  QT_TRANSLATE_NOOP("Beamer", "movie"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkmovie"),
  QT_TRANSLATE_NOOP("Beamer", "animate"),
  QT_TRANSLATE_NOOP("Beamer", "animatevalue"),
  QT_TRANSLATE_NOOP("Beamer", "multiinclude"),
  QT_TRANSLATE_NOOP("Beamer", "sound"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinksound"),
  QT_TRANSLATE_NOOP("Beamer", "hyperlinkmute"),
  QT_TRANSLATE_NOOP("Beamer", "transblindshorizontal"),
  QT_TRANSLATE_NOOP("Beamer", "transblindsvertical"),
  QT_TRANSLATE_NOOP("Beamer", "transboxin"),
  QT_TRANSLATE_NOOP("Beamer", "transboxout"),
  QT_TRANSLATE_NOOP("Beamer", "transdissolve"),
  QT_TRANSLATE_NOOP("Beamer", "transglitter"),
  QT_TRANSLATE_NOOP("Beamer", "transsplitverticalin"),
  QT_TRANSLATE_NOOP("Beamer", "transsplitverticalout"),
  QT_TRANSLATE_NOOP("Beamer", "transsplithorizontalin"),
  QT_TRANSLATE_NOOP("Beamer", "transsplithorizontalout"),
  QT_TRANSLATE_NOOP("Beamer", "transwipe"),
  QT_TRANSLATE_NOOP("Beamer", "transduration"),
  QT_TRANSLATE_NOOP("Beamer", "item"),
  QT_TRANSLATE_NOOP("Beamer", "label"),
  QT_TRANSLATE_NOOP("Beamer", "bibitem"),
  QT_TRANSLATE_NOOP("Beamer", "column"),
  QT_TRANSLATE_NOOP("Beamer", "note"),
  QT_TRANSLATE_NOOP("Beamer", "pause"),
  QT_TRANSLATE_NOOP("Beamer", "onslide"),
  QT_TRANSLATE_NOOP("Beamer", "only"),
  QT_TRANSLATE_NOOP("Beamer", "uncover"),
  QT_TRANSLATE_NOOP("Beamer", "visible"),
  QT_TRANSLATE_NOOP("Beamer", "invisible"),
  QT_TRANSLATE_NOOP("Beamer", "alt"),
  QT_TRANSLATE_NOOP("Beamer", "temporal"),
  QT_TRANSLATE_NOOP("Beamer", "resetcounteronoverlays"),
  QT_TRANSLATE_NOOP("Beamer", "resetcountonoverlays"),
  QT_TRANSLATE_NOOP("Beamer", "action"),
  QT_TRANSLATE_NOOP("Beamer", "beamerdefaultoverlayspecification"),
  QT_TRANSLATE_NOOP("Beamer", "structure"),
  QT_TRANSLATE_NOOP("Beamer", "alert"),
  QT_TRANSLATE_NOOP("Beamer", "begin"),
  QT_TRANSLATE_NOOP("Beamer", "end"),
  QT_TRANSLATE_NOOP("Beamer", "titlepage"),
  QT_TRANSLATE_NOOP("Beamer", "partpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertauthor"),
  QT_TRANSLATE_NOOP("Beamer", "insertdate"),
  QT_TRANSLATE_NOOP("Beamer", "insertinstitute"),
  QT_TRANSLATE_NOOP("Beamer", "inserttitle"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubtitle"),
  QT_TRANSLATE_NOOP("Beamer", "inserttitlegraphic"),
  QT_TRANSLATE_NOOP("Beamer", "insertpart"),
  QT_TRANSLATE_NOOP("Beamer", "insertpartnumber"),
  QT_TRANSLATE_NOOP("Beamer", "insertpartromannumber"),
  QT_TRANSLATE_NOOP("Beamer", "inserttocsection"),
  QT_TRANSLATE_NOOP("Beamer", "inserttocsectionnumber"),
  QT_TRANSLATE_NOOP("Beamer", "inserttocsubsection"),
  QT_TRANSLATE_NOOP("Beamer", "inserttocsubsectionnumber"),
  QT_TRANSLATE_NOOP("Beamer", "inserttocsubsubsection"),
  QT_TRANSLATE_NOOP("Beamer", "inserttocsubsubsectionnumber"),
  QT_TRANSLATE_NOOP("Beamer", "insertcontinuationcount"),
  QT_TRANSLATE_NOOP("Beamer", "insertcontinuationcountroman"),
  QT_TRANSLATE_NOOP("Beamer", "insertcontinuationtext"),
  QT_TRANSLATE_NOOP("Beamer", "insertnavigation"),
  QT_TRANSLATE_NOOP("Beamer", "insertpagenumber"),
  QT_TRANSLATE_NOOP("Beamer", "insertsection"),
  QT_TRANSLATE_NOOP("Beamer", "insertsectionnavigation"),
  QT_TRANSLATE_NOOP("Beamer", "insertsectionnavigationhorizontal"),
  QT_TRANSLATE_NOOP("Beamer", "insertshortauthor"),
  QT_TRANSLATE_NOOP("Beamer", "insertshortdate"),
  QT_TRANSLATE_NOOP("Beamer", "insertshortinstitute"),
  QT_TRANSLATE_NOOP("Beamer", "insertshortpart"),
  QT_TRANSLATE_NOOP("Beamer", "insertshorttitle"),
  QT_TRANSLATE_NOOP("Beamer", "insertshortsubtitle"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsection"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsubsection"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsectionnavigation"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsectionnavigationhorizontal"),
  QT_TRANSLATE_NOOP("Beamer", "insertverticalnavigation"),
  QT_TRANSLATE_NOOP("Beamer", "insertframenumber"),
  QT_TRANSLATE_NOOP("Beamer", "inserttotalframenumber"),
  QT_TRANSLATE_NOOP("Beamer", "insertframestartpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertframeendpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsectionstartpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsectionendpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertsectionstartpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertsectionendpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertpartstartpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertpartendpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertpresentationstartpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertpresentationendpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertappendixstartpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertappendixendpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertdocumentstartpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertdocumentendpage"),
  QT_TRANSLATE_NOOP("Beamer", "insertsectionhead"),
  QT_TRANSLATE_NOOP("Beamer", "insertsectionheadnumber"),
  QT_TRANSLATE_NOOP("Beamer", "insertpartheadnumber"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsectionhead"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsectionheadnumber"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsubsectionhead"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsubsectionheadnumber"),
  QT_TRANSLATE_NOOP("Beamer", "insertslidenavigationsymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertframenavigationsymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsectionnavigationsymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertsectionnavigationsymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertdocnavigationsymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertbackfindforwardnavigationsymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertlogo"),
  QT_TRANSLATE_NOOP("Beamer", "insertframetitle"),
  QT_TRANSLATE_NOOP("Beamer", "insertframesubtitle"),
  QT_TRANSLATE_NOOP("Beamer", "insertbiblabel"),
  QT_TRANSLATE_NOOP("Beamer", "insertbuttontext"),
  QT_TRANSLATE_NOOP("Beamer", "insertgotosymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertskipsymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertreturnsymbol"),
  QT_TRANSLATE_NOOP("Beamer", "insertenumlabel"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubenumlabel"),
  QT_TRANSLATE_NOOP("Beamer", "insertsubsubenumlabel"),
  QT_TRANSLATE_NOOP("Beamer", "insertdescriptionitem"),
  QT_TRANSLATE_NOOP("Beamer", "insertblocktitle"),
  QT_TRANSLATE_NOOP("Beamer", "inserttheoremblockenv"),
  QT_TRANSLATE_NOOP("Beamer", "inserttheoremheadfont"),
  QT_TRANSLATE_NOOP("Beamer", "inserttheoremname"),
  QT_TRANSLATE_NOOP("Beamer", "inserttheoremnumber"),
  QT_TRANSLATE_NOOP("Beamer", "inserttheoremaddition"),
  QT_TRANSLATE_NOOP("Beamer", "inserttheorempunctuation"),
  QT_TRANSLATE_NOOP("Beamer", "insertcaption"),
  QT_TRANSLATE_NOOP("Beamer", "insertcaptionname"),
  QT_TRANSLATE_NOOP("Beamer", "insertcaptionnumber"),
  QT_TRANSLATE_NOOP("Beamer", "handout"),
  QT_TRANSLATE_NOOP("Beamer", "trans"),
  QT_TRANSLATE_NOOP("Beamer", "aspectratio"),
  QT_TRANSLATE_NOOP("Beamer", "8pt"),
  QT_TRANSLATE_NOOP("Beamer", "9pt"),
  QT_TRANSLATE_NOOP("Beamer", "10pt"),
  QT_TRANSLATE_NOOP("Beamer", "smaller"),
  QT_TRANSLATE_NOOP("Beamer", "11pt"),
  QT_TRANSLATE_NOOP("Beamer", "12pt"),
  QT_TRANSLATE_NOOP("Beamer", "bigger"),
  QT_TRANSLATE_NOOP("Beamer", "14pt"),
  QT_TRANSLATE_NOOP("Beamer", "17pt"),
  QT_TRANSLATE_NOOP("Beamer", "20pt"),
  QT_TRANSLATE_NOOP("Beamer", "draft"),
  QT_TRANSLATE_NOOP("Beamer", "compress"),
  QT_TRANSLATE_NOOP("Beamer", "b"),
  QT_TRANSLATE_NOOP("Beamer", "c"),
  QT_TRANSLATE_NOOP("Beamer", "t"),
  QT_TRANSLATE_NOOP("Beamer", "color"),
  QT_TRANSLATE_NOOP("Beamer", "xcolor"),
  QT_TRANSLATE_NOOP("Beamer", "ucs"),
  QT_TRANSLATE_NOOP("Beamer", "utf8x"),
  QT_TRANSLATE_NOOP("Beamer", "utf8"),
  QT_TRANSLATE_NOOP("Beamer", "prosper"),
  QT_TRANSLATE_NOOP("Beamer", "seminar"),
  QT_TRANSLATE_NOOP("Beamer", "foils"),
  QT_TRANSLATE_NOOP("Beamer", "hyperref"),
  QT_TRANSLATE_NOOP("Beamer", "usepdftitle"),
  QT_TRANSLATE_NOOP("Beamer", "envcountsect"),
  QT_TRANSLATE_NOOP("Beamer", "notheorems"),
  QT_TRANSLATE_NOOP("Beamer", "noamsthm"),
  QT_TRANSLATE_NOOP("Beamer", "beamer"),
  QT_TRANSLATE_NOOP("Beamer", "second"),
  QT_TRANSLATE_NOOP("Beamer", "article"),
  QT_TRANSLATE_NOOP("Beamer", "all"),
  QT_TRANSLATE_NOOP("Beamer", "presentation"),
  QT_TRANSLATE_NOOP("Beamer", "default"),
  QT_TRANSLATE_NOOP("Beamer", "boxes"),
  QT_TRANSLATE_NOOP("Beamer", "Bergen"),
  QT_TRANSLATE_NOOP("Beamer", "Boadilla"),
  QT_TRANSLATE_NOOP("Beamer", "Madrid"),
  QT_TRANSLATE_NOOP("Beamer", "AnnArbor"),
  QT_TRANSLATE_NOOP("Beamer", "CambridgeUS"),
  QT_TRANSLATE_NOOP("Beamer", "Pittsburgh"),
  QT_TRANSLATE_NOOP("Beamer", "Rochester"),
  QT_TRANSLATE_NOOP("Beamer", "Antibes"),
  QT_TRANSLATE_NOOP("Beamer", "JuanLesPins"),
  QT_TRANSLATE_NOOP("Beamer", "Montpellier"),
  QT_TRANSLATE_NOOP("Beamer", "Berkeley"),
  QT_TRANSLATE_NOOP("Beamer", "PaloAlto"),
  QT_TRANSLATE_NOOP("Beamer", "Goettingen"),
  QT_TRANSLATE_NOOP("Beamer", "Marburg"),
  QT_TRANSLATE_NOOP("Beamer", "Hannover"),
  QT_TRANSLATE_NOOP("Beamer", "Berlin"),
  QT_TRANSLATE_NOOP("Beamer", "Ilmenau"),
  QT_TRANSLATE_NOOP("Beamer", "Dresden"),
  QT_TRANSLATE_NOOP("Beamer", "Darmstadt"),
  QT_TRANSLATE_NOOP("Beamer", "Frankfurt"),
  QT_TRANSLATE_NOOP("Beamer", "Singapore"),
  QT_TRANSLATE_NOOP("Beamer", "Szeged"),
  QT_TRANSLATE_NOOP("Beamer", "Copenhagen"),
  QT_TRANSLATE_NOOP("Beamer", "Luebeck"),
  QT_TRANSLATE_NOOP("Beamer", "Malmoe"),
  QT_TRANSLATE_NOOP("Beamer", "Warsaw"),
  QT_TRANSLATE_NOOP("Beamer", "circles"),
  QT_TRANSLATE_NOOP("Beamer", "rectangles"),
  QT_TRANSLATE_NOOP("Beamer", "rounded"),
  QT_TRANSLATE_NOOP("Beamer", "inmargin"),
  QT_TRANSLATE_NOOP("Beamer", "infolines"),
  QT_TRANSLATE_NOOP("Beamer", "miniframes"),
  QT_TRANSLATE_NOOP("Beamer", "smoothbars"),
  QT_TRANSLATE_NOOP("Beamer", "sidebar"),
  QT_TRANSLATE_NOOP("Beamer", "split"),
  QT_TRANSLATE_NOOP("Beamer", "shadow"),
  QT_TRANSLATE_NOOP("Beamer", "tree"),
  QT_TRANSLATE_NOOP("Beamer", "smoothtree"),
  QT_TRANSLATE_NOOP("Beamer", "sidebartab"),
  QT_TRANSLATE_NOOP("Beamer", "albatross"),
  QT_TRANSLATE_NOOP("Beamer", "beetle"),
  QT_TRANSLATE_NOOP("Beamer", "crane"),
  QT_TRANSLATE_NOOP("Beamer", "dove"),
  QT_TRANSLATE_NOOP("Beamer", "fly"),
  QT_TRANSLATE_NOOP("Beamer", "seagull"),
  QT_TRANSLATE_NOOP("Beamer", "wolverine"),
  QT_TRANSLATE_NOOP("Beamer", "beaver"),
  QT_TRANSLATE_NOOP("Beamer", "lily"),
  QT_TRANSLATE_NOOP("Beamer", "orchid"),
  QT_TRANSLATE_NOOP("Beamer", "rose"),
  QT_TRANSLATE_NOOP("Beamer", "whale"),
  QT_TRANSLATE_NOOP("Beamer", "seahorse"),
  QT_TRANSLATE_NOOP("Beamer", "dolphin"),
  QT_TRANSLATE_NOOP("Beamer", "professionalfonts"),
  QT_TRANSLATE_NOOP("Beamer", "serif"),
  QT_TRANSLATE_NOOP("Beamer", "structurebold"),
  QT_TRANSLATE_NOOP("Beamer", "structureitalicserif"),
  QT_TRANSLATE_NOOP("Beamer", "structuresmallcapsserif"),
  QT_TRANSLATE_NOOP("Beamer", "headheight"),
  QT_TRANSLATE_NOOP("Beamer", "footheight"),
  QT_TRANSLATE_NOOP("Beamer", "secheader"),
  QT_TRANSLATE_NOOP("Beamer", "height"),
  QT_TRANSLATE_NOOP("Beamer", "hideallsubsections"),
  QT_TRANSLATE_NOOP("Beamer", "hideothersubsections"),
  QT_TRANSLATE_NOOP("Beamer", "left"),
  QT_TRANSLATE_NOOP("Beamer", "right"),
  QT_TRANSLATE_NOOP("Beamer", "width"),
  QT_TRANSLATE_NOOP("Beamer", "footline"),
  QT_TRANSLATE_NOOP("Beamer", "hooks"),
  QT_TRANSLATE_NOOP("Beamer", "rgb"),
  QT_TRANSLATE_NOOP("Beamer", "cmyk"),
  QT_TRANSLATE_NOOP("Beamer", "cmy"),
  QT_TRANSLATE_NOOP("Beamer", "hsb"),
  QT_TRANSLATE_NOOP("Beamer", "named"),
  QT_TRANSLATE_NOOP("Beamer", "overlystylish"),
  QT_TRANSLATE_NOOP("Beamer", "stillsansserifmath"),
  QT_TRANSLATE_NOOP("Beamer", "stillsansserifsmall"),
  QT_TRANSLATE_NOOP("Beamer", "stillsansseriflarge"),
  QT_TRANSLATE_NOOP("Beamer", "stillsansseriftext"),
  QT_TRANSLATE_NOOP("Beamer", "onlymath"),
  QT_TRANSLATE_NOOP("Beamer", "onlysmall"),
  QT_TRANSLATE_NOOP("Beamer", "onlylarge"),
  QT_TRANSLATE_NOOP("Beamer", "frametitle continuation"),
  QT_TRANSLATE_NOOP("Beamer", "headline"),
  QT_TRANSLATE_NOOP("Beamer", "sidebar left"),
  QT_TRANSLATE_NOOP("Beamer", "sidebar right"),
  QT_TRANSLATE_NOOP("Beamer", "mini frame"),
  QT_TRANSLATE_NOOP("Beamer", "section in head/foot"),
  QT_TRANSLATE_NOOP("Beamer", "section in sidebar"),
  QT_TRANSLATE_NOOP("Beamer", "subsection in head/foot"),
  QT_TRANSLATE_NOOP("Beamer", "subsection in sidebar"),
  QT_TRANSLATE_NOOP("Beamer", "subsubsection in head/foot"),
  QT_TRANSLATE_NOOP("Beamer", "subsubsection in sidebar"),
  QT_TRANSLATE_NOOP("Beamer", "navigation symbols"),
  QT_TRANSLATE_NOOP("Beamer", "background canvas"),
  QT_TRANSLATE_NOOP("Beamer", "background"),
  QT_TRANSLATE_NOOP("Beamer", "title page"),
  QT_TRANSLATE_NOOP("Beamer", "section in toc"),
  QT_TRANSLATE_NOOP("Beamer", "section in toc shaded"),
  QT_TRANSLATE_NOOP("Beamer", "subsection in toc"),
  QT_TRANSLATE_NOOP("Beamer", "subsection in toc shaded"),
  QT_TRANSLATE_NOOP("Beamer", "subsubsection in toc"),
  QT_TRANSLATE_NOOP("Beamer", "subsubsection in toc shaded"),
  QT_TRANSLATE_NOOP("Beamer", "part page"),
  QT_TRANSLATE_NOOP("Beamer", "bibliography entry author"),
  QT_TRANSLATE_NOOP("Beamer", "bibliography entry title"),
  QT_TRANSLATE_NOOP("Beamer", "bibliography entry journal"),
  QT_TRANSLATE_NOOP("Beamer", "bibliography entry note"),
  QT_TRANSLATE_NOOP("Beamer", "bibliography item"),
  QT_TRANSLATE_NOOP("Beamer", "button"),
  QT_TRANSLATE_NOOP("Beamer", "itemize item"),
  QT_TRANSLATE_NOOP("Beamer", "itemize subitem"),
  QT_TRANSLATE_NOOP("Beamer", "itemize subsubitem"),
  QT_TRANSLATE_NOOP("Beamer", "enumerate item"),
  QT_TRANSLATE_NOOP("Beamer", "enumerate subitem"),
  QT_TRANSLATE_NOOP("Beamer", "enumerate subsubitem"),
  QT_TRANSLATE_NOOP("Beamer", "enumerate mini template"),
  QT_TRANSLATE_NOOP("Beamer", "description item"),
  QT_TRANSLATE_NOOP("Beamer", "qed symbol"),
  QT_TRANSLATE_NOOP("Beamer", "caption"),
  QT_TRANSLATE_NOOP("Beamer", "abstract title"),
  QT_TRANSLATE_NOOP("Beamer", "note page"),
  QT_TRANSLATE_NOOP("Beamer", "frame begin"),
  QT_TRANSLATE_NOOP("Beamer", "frame end"),
  QT_TRANSLATE_NOOP("Beamer", "sidebar canvas left"),
  QT_TRANSLATE_NOOP("Beamer", "sidebar canvas right"),
  QT_TRANSLATE_NOOP("Beamer", "mini frames"),
  QT_TRANSLATE_NOOP("Beamer", "mini frame in current subsection"),
  QT_TRANSLATE_NOOP("Beamer", "mini frame in other subsection"),
  QT_TRANSLATE_NOOP("Beamer", "section in head/foot shaded"),
  QT_TRANSLATE_NOOP("Beamer", "section in sidebar shaded"),
  QT_TRANSLATE_NOOP("Beamer", "subsection in head/foot shaded"),
  QT_TRANSLATE_NOOP("Beamer", "subsection in sidebar shaded"),
  QT_TRANSLATE_NOOP("Beamer", "subsubsection in head/foot shaded"),
  QT_TRANSLATE_NOOP("Beamer", "subsubsection in sidebar shaded"),
  QT_TRANSLATE_NOOP("Beamer", "sections/subsections in toc"),
  QT_TRANSLATE_NOOP("Beamer", "sections/subsections in toc shaded"),
  QT_TRANSLATE_NOOP("Beamer", "itemize items"),
  QT_TRANSLATE_NOOP("Beamer", "enumerate items"),
  QT_TRANSLATE_NOOP("Beamer", "itemize/enumerate body begin"),
  QT_TRANSLATE_NOOP("Beamer", "itemize/enumerate body end"),
  QT_TRANSLATE_NOOP("Beamer", "items"),
  QT_TRANSLATE_NOOP("Beamer", "structure begin"),
  QT_TRANSLATE_NOOP("Beamer", "structure end"),
  QT_TRANSLATE_NOOP("Beamer", "alerted text begin"),
  QT_TRANSLATE_NOOP("Beamer", "alerted text end"),
  QT_TRANSLATE_NOOP("Beamer", "blocks"),
  QT_TRANSLATE_NOOP("Beamer", "block begin"),
  QT_TRANSLATE_NOOP("Beamer", "block end"),
  QT_TRANSLATE_NOOP("Beamer", "block alerted begin"),
  QT_TRANSLATE_NOOP("Beamer", "block alerted end"),
  QT_TRANSLATE_NOOP("Beamer", "block example begin"),
  QT_TRANSLATE_NOOP("Beamer", "block example end"),
  QT_TRANSLATE_NOOP("Beamer", "theorems"),
  QT_TRANSLATE_NOOP("Beamer", "theorem begin"),
  QT_TRANSLATE_NOOP("Beamer", "theorem end"),
  QT_TRANSLATE_NOOP("Beamer", "abstract begin"),
  QT_TRANSLATE_NOOP("Beamer", "abstract end"),
  QT_TRANSLATE_NOOP("Beamer", "verse begin"),
  QT_TRANSLATE_NOOP("Beamer", "verse end"),
  QT_TRANSLATE_NOOP("Beamer", "quotation begin"),
  QT_TRANSLATE_NOOP("Beamer", "quotation end"),
  QT_TRANSLATE_NOOP("Beamer", "quote begin"),
  QT_TRANSLATE_NOOP("Beamer", "quote end"),
  QT_TRANSLATE_NOOP("Beamer", "page number in head/foot"),
  QT_TRANSLATE_NOOP("Beamer", "item projected"),
  QT_TRANSLATE_NOOP("Beamer", "subitem"),
  QT_TRANSLATE_NOOP("Beamer", "subitem projected"),
  QT_TRANSLATE_NOOP("Beamer", "subsubitem"),
  QT_TRANSLATE_NOOP("Beamer", "subsubitem projected"),
  QT_TRANSLATE_NOOP("Beamer", "alerted text"),
  QT_TRANSLATE_NOOP("Beamer", "block title"),
  QT_TRANSLATE_NOOP("Beamer", "block body"),
  QT_TRANSLATE_NOOP("Beamer", "block title alerted"),
  QT_TRANSLATE_NOOP("Beamer", "block body alerted"),
  QT_TRANSLATE_NOOP("Beamer", "block title example"),
  QT_TRANSLATE_NOOP("Beamer", "block body example"),
  QT_TRANSLATE_NOOP("Beamer", "caption name"),
  QT_TRANSLATE_NOOP("Beamer", "footnote mark"),
  QT_TRANSLATE_NOOP("Beamer", "normal text"),
  QT_TRANSLATE_NOOP("Beamer", "example text"),
  QT_TRANSLATE_NOOP("Beamer", "titlelike"),
  QT_TRANSLATE_NOOP("Beamer", "button border"),
  QT_TRANSLATE_NOOP("Beamer", "local structure"),
  QT_TRANSLATE_NOOP("Beamer", "math text"),
  QT_TRANSLATE_NOOP("Beamer", "math text inlined"),
  QT_TRANSLATE_NOOP("Beamer", "math text displayed"),
  QT_TRANSLATE_NOOP("Beamer", "normal text in math text"),
  QT_TRANSLATE_NOOP("Beamer", "palette primary"),
  QT_TRANSLATE_NOOP("Beamer", "palette secondary"),
  QT_TRANSLATE_NOOP("Beamer", "palette tertiary"),
  QT_TRANSLATE_NOOP("Beamer", "palette quaternary"),
  QT_TRANSLATE_NOOP("Beamer", "palette sidebar primary"),
  QT_TRANSLATE_NOOP("Beamer", "palette sidebar secondary"),
  QT_TRANSLATE_NOOP("Beamer", "palette sidebar tertiary"),
  QT_TRANSLATE_NOOP("Beamer", "palette sidebar quaternary"),
  QT_TRANSLATE_NOOP("Beamer", "separation line"),
  QT_TRANSLATE_NOOP("Beamer", "upper separation line head"),
  QT_TRANSLATE_NOOP("Beamer", "middle separation line head"),
  QT_TRANSLATE_NOOP("Beamer", "lower separation line head"),
  QT_TRANSLATE_NOOP("Beamer", "upper separation line foot"),
  QT_TRANSLATE_NOOP("Beamer", "middle separation line foot"),
  QT_TRANSLATE_NOOP("Beamer", "lower separation line foot"),
  QT_TRANSLATE_NOOP("Beamer", "tiny structure"),
  QT_TRANSLATE_NOOP("Beamer", "roman"),
  QT_TRANSLATE_NOOP("Beamer", "from second"),
  QT_TRANSLATE_NOOP("Beamer", "infolines theme"),
  QT_TRANSLATE_NOOP("Beamer", "miniframes theme"),
  QT_TRANSLATE_NOOP("Beamer", "sidebar theme"),
  QT_TRANSLATE_NOOP("Beamer", "smoothtree theme"),
  QT_TRANSLATE_NOOP("Beamer", "smoothbars theme"),
  QT_TRANSLATE_NOOP("Beamer", "split theme"),
  QT_TRANSLATE_NOOP("Beamer", "text line"),
  QT_TRANSLATE_NOOP("Beamer", "page number"),
  QT_TRANSLATE_NOOP("Beamer", "frame number"),
  QT_TRANSLATE_NOOP("Beamer", "vertical shading"),
  QT_TRANSLATE_NOOP("Beamer", "horizontal shading"),
  QT_TRANSLATE_NOOP("Beamer", "top"),
  QT_TRANSLATE_NOOP("Beamer", "bottom"),
  QT_TRANSLATE_NOOP("Beamer", "middle"),
  QT_TRANSLATE_NOOP("Beamer", "midpoint"),
  QT_TRANSLATE_NOOP("Beamer", "box"),
  QT_TRANSLATE_NOOP("Beamer", "tick"),
  QT_TRANSLATE_NOOP("Beamer", "horizontal"),
  QT_TRANSLATE_NOOP("Beamer", "vertical"),
  QT_TRANSLATE_NOOP("Beamer", "only frame symbol"),
  QT_TRANSLATE_NOOP("Beamer", "shadow theme"),
  QT_TRANSLATE_NOOP("Beamer", "grid"),
  QT_TRANSLATE_NOOP("Beamer", "step"),
  QT_TRANSLATE_NOOP("Beamer", "sections numbered"),
  QT_TRANSLATE_NOOP("Beamer", "subsections numbered"),
  QT_TRANSLATE_NOOP("Beamer", "circle"),
  QT_TRANSLATE_NOOP("Beamer", "square"),
  QT_TRANSLATE_NOOP("Beamer", "ball"),
  QT_TRANSLATE_NOOP("Beamer", "ball unnumbered"),
  QT_TRANSLATE_NOOP("Beamer", "book"),
  QT_TRANSLATE_NOOP("Beamer", "triangle"),
  QT_TRANSLATE_NOOP("Beamer", "text"),
  QT_TRANSLATE_NOOP("Beamer", "normal font"),
  QT_TRANSLATE_NOOP("Beamer", "numbered"),
  QT_TRANSLATE_NOOP("Beamer", "ams style"),
  QT_TRANSLATE_NOOP("Beamer", "caption name own line"),
  QT_TRANSLATE_NOOP("Beamer", "plain"),
  QT_TRANSLATE_NOOP("Beamer", "fg"),
  QT_TRANSLATE_NOOP("Beamer", "bg"),
  QT_TRANSLATE_NOOP("Beamer", "parent"),
  QT_TRANSLATE_NOOP("Beamer", "use"),
  QT_TRANSLATE_NOOP("Beamer", "transparent"),
  QT_TRANSLATE_NOOP("Beamer", "dynamic"),
  QT_TRANSLATE_NOOP("Beamer", "highly dynamic"),
  QT_TRANSLATE_NOOP("Beamer", "still covered"),
  QT_TRANSLATE_NOOP("Beamer", "again covered"),
  QT_TRANSLATE_NOOP("Beamer", "size"),
  QT_TRANSLATE_NOOP("Beamer", "size*"),
  QT_TRANSLATE_NOOP("Beamer", "shape"),
  QT_TRANSLATE_NOOP("Beamer", "shape*"),
  QT_TRANSLATE_NOOP("Beamer", "series"),
  QT_TRANSLATE_NOOP("Beamer", "series*"),
  QT_TRANSLATE_NOOP("Beamer", "family"),
  QT_TRANSLATE_NOOP("Beamer", "family*"),
  QT_TRANSLATE_NOOP("Beamer", "hide notes"),
  QT_TRANSLATE_NOOP("Beamer", "show notes"),
  QT_TRANSLATE_NOOP("Beamer", "show notes on second screen"),
  QT_TRANSLATE_NOOP("Beamer", "show only notes"),
  QT_TRANSLATE_NOOP("Beamer", "second mode text on second screen"),
  QT_TRANSLATE_NOOP("Beamer", "always typeset second mode"),
  QT_TRANSLATE_NOOP("Beamer", "previous slide on second screen"),
  QT_TRANSLATE_NOOP("Beamer", "text margin left"),
  QT_TRANSLATE_NOOP("Beamer", "text margin right"),
  QT_TRANSLATE_NOOP("Beamer", "sidebar width left"),
  QT_TRANSLATE_NOOP("Beamer", "sidebar width right"),
  QT_TRANSLATE_NOOP("Beamer", "description width"),
  QT_TRANSLATE_NOOP("Beamer", "description width of"),
  QT_TRANSLATE_NOOP("Beamer", "mini frame size"),
  QT_TRANSLATE_NOOP("Beamer", "mini frame offset"),
  QT_TRANSLATE_NOOP("Beamer", "allowdisplaybreaks"),
  QT_TRANSLATE_NOOP("Beamer", "allowframebreaks"),
  QT_TRANSLATE_NOOP("Beamer", "fragile"),
  QT_TRANSLATE_NOOP("Beamer", "environment"),
  QT_TRANSLATE_NOOP("Beamer", "shrink"),
  QT_TRANSLATE_NOOP("Beamer", "squeeze"),
  QT_TRANSLATE_NOOP("Beamer", "currentsection"),
  QT_TRANSLATE_NOOP("Beamer", "currentsubsection"),
  QT_TRANSLATE_NOOP("Beamer", "firstsection"),
  QT_TRANSLATE_NOOP("Beamer", "pausesections"),
  QT_TRANSLATE_NOOP("Beamer", "pausesubsections"),
  QT_TRANSLATE_NOOP("Beamer", "sections"),
  QT_TRANSLATE_NOOP("Beamer", "sectionstyle"),
  QT_TRANSLATE_NOOP("Beamer", "subsectionstyle"),
  QT_TRANSLATE_NOOP("Beamer", "border"),
  QT_TRANSLATE_NOOP("Beamer", "autostart"),
  QT_TRANSLATE_NOOP("Beamer", "borderwidth"),
  QT_TRANSLATE_NOOP("Beamer", "depth"),
  QT_TRANSLATE_NOOP("Beamer", "duration"),
  QT_TRANSLATE_NOOP("Beamer", "externalviewer"),
  QT_TRANSLATE_NOOP("Beamer", "loop"),
  QT_TRANSLATE_NOOP("Beamer", "once"),
  QT_TRANSLATE_NOOP("Beamer", "open"),
  QT_TRANSLATE_NOOP("Beamer", "palindrome"),
  QT_TRANSLATE_NOOP("Beamer", "poster"),
  QT_TRANSLATE_NOOP("Beamer", "repeat"),
  QT_TRANSLATE_NOOP("Beamer", "showcontrols"),
  QT_TRANSLATE_NOOP("Beamer", "start"),
  QT_TRANSLATE_NOOP("Beamer", "play"),
  QT_TRANSLATE_NOOP("Beamer", "resume"),
  QT_TRANSLATE_NOOP("Beamer", "stop"),
  QT_TRANSLATE_NOOP("Beamer", "graphics"),
  QT_TRANSLATE_NOOP("Beamer", "format"),
  QT_TRANSLATE_NOOP("Beamer", "automute"),
  QT_TRANSLATE_NOOP("Beamer", "bitspersample"),
  QT_TRANSLATE_NOOP("Beamer", "channels"),
  QT_TRANSLATE_NOOP("Beamer", "encoding"),
  QT_TRANSLATE_NOOP("Beamer", "inlinesound"),
  QT_TRANSLATE_NOOP("Beamer", "mixsound"),
  QT_TRANSLATE_NOOP("Beamer", "samplingrate"),
  QT_TRANSLATE_NOOP("Beamer", "direction"),
  QT_TRANSLATE_NOOP("Beamer", "onlyenv"),
  QT_TRANSLATE_NOOP("Beamer", "altenv"),
  QT_TRANSLATE_NOOP("Beamer", "overlayarea"),
  QT_TRANSLATE_NOOP("Beamer", "overprint"),
  QT_TRANSLATE_NOOP("Beamer", "actionenv"),
  QT_TRANSLATE_NOOP("Beamer", "thebibliography"),
  QT_TRANSLATE_NOOP("Beamer", "itemize"),
  QT_TRANSLATE_NOOP("Beamer", "enumerate"),
  QT_TRANSLATE_NOOP("Beamer", "description"),
  QT_TRANSLATE_NOOP("Beamer", "structureenv"),
  QT_TRANSLATE_NOOP("Beamer", "alertenv"),
  QT_TRANSLATE_NOOP("Beamer", "block"),
  QT_TRANSLATE_NOOP("Beamer", "alertblock"),
  QT_TRANSLATE_NOOP("Beamer", "exampleblock"),
  QT_TRANSLATE_NOOP("Beamer", "theorem"),
  QT_TRANSLATE_NOOP("Beamer", "corollary"),
  QT_TRANSLATE_NOOP("Beamer", "fact"),
  QT_TRANSLATE_NOOP("Beamer", "lemma"),
  QT_TRANSLATE_NOOP("Beamer", "definition"),
  QT_TRANSLATE_NOOP("Beamer", "definitions"),
  QT_TRANSLATE_NOOP("Beamer", "example"),
  QT_TRANSLATE_NOOP("Beamer", "examples"),
  QT_TRANSLATE_NOOP("Beamer", "proof"),
  QT_TRANSLATE_NOOP("Beamer", "Problem"),
  QT_TRANSLATE_NOOP("Beamer", "Loesung"),
  QT_TRANSLATE_NOOP("Beamer", "Definition"),
  QT_TRANSLATE_NOOP("Beamer", "Satz"),
  QT_TRANSLATE_NOOP("Beamer", "Beweis"),
  QT_TRANSLATE_NOOP("Beamer", "Folgerung"),
  QT_TRANSLATE_NOOP("Beamer", "Lemma"),
  QT_TRANSLATE_NOOP("Beamer", "Fakt"),
  QT_TRANSLATE_NOOP("Beamer", "Beispiel"),
  QT_TRANSLATE_NOOP("Beamer", "Beispiele"),
  QT_TRANSLATE_NOOP("Beamer", "beamercolorbox"),
  QT_TRANSLATE_NOOP("Beamer", "beamerboxesrounded"),
  QT_TRANSLATE_NOOP("Beamer", "columns"),
  QT_TRANSLATE_NOOP("Beamer", "semiverbatim"),
  QT_TRANSLATE_NOOP("Beamer", "abstract"),
  QT_TRANSLATE_NOOP("Beamer", "verse"),
  QT_TRANSLATE_NOOP("Beamer", "quotation"),
  QT_TRANSLATE_NOOP("Beamer", "quote"),
  QT_TRANSLATE_NOOP("Beamer", "wd"),
  QT_TRANSLATE_NOOP("Beamer", "dp"),
  QT_TRANSLATE_NOOP("Beamer", "ht"),
  QT_TRANSLATE_NOOP("Beamer", "center"),
  QT_TRANSLATE_NOOP("Beamer", "leftskip"),
  QT_TRANSLATE_NOOP("Beamer", "rightskip"),
  QT_TRANSLATE_NOOP("Beamer", "sep"),
  QT_TRANSLATE_NOOP("Beamer", "colsep"),
  QT_TRANSLATE_NOOP("Beamer", "colsep*"),
  QT_TRANSLATE_NOOP("Beamer", "ignorebg"),
  QT_TRANSLATE_NOOP("Beamer", "vmode"),
  QT_TRANSLATE_NOOP("Beamer", "lower"),
  QT_TRANSLATE_NOOP("Beamer", "upper"),
  QT_TRANSLATE_NOOP("Beamer", "onlytextwidth"),
  QT_TRANSLATE_NOOP("Beamer", "T"),
  QT_TRANSLATE_NOOP("Beamer", "totalwidth"),
  QT_TRANSLATE_NOOP("Beamer", "paragraph"),
  QT_TRANSLATE_NOOP("Beamer", "overlay specification"),
  QT_TRANSLATE_NOOP("Beamer", "default overlay specification"),
  QT_TRANSLATE_NOOP("Beamer", "modifier"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "theme names"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "color theme names"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options"),
  QT_TRANSLATE_NOOP("Beamer", "options")
};

static XWTeXHash * beamerKeyWordTab = 0;

static void loadBeamerPool()
{
	if (!beamerKeyWordTab)
	{
		beamerKeyWordTab = new XWTeXHash(BEAMER_MIN_KEYWORD);
		beamerKeyWordTab->loadFile(2000, 50 * 1024, "beamer.pool");
	}
}

QString getBeamerString(qint32 s)
{
	loadBeamerPool();
	if (s >= BEAMER_MIN_KEYWORD && s <= BMcolumnsopt)
		return beamerKeyWordTab->getString(s);
		
	return QString();
}

QString getBeamerTranslate(int type)
{
	loadBeamerPool();
	if (type >= BEAMER_MIN_KEYWORD && type <= BMcolumnsopt)
		return qApp->translate("Beamer", beamer_strings[type - BEAMER_MIN_KEYWORD]);
		
	return beamerKeyWordTab->getString((qint32)type);
}

qint32 lookupBeamerID(qint32 * buf, qint32 l)
{
	loadBeamerPool();
	return beamerKeyWordTab->lookupID(buf, l);
}

qint32 lookupBeamerID(const QString & str)
{
	loadBeamerPool();
	return beamerKeyWordTab->lookupID(str);
}
